/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.4 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTEXPR3 = 6;
  public int JJTTERM = 7;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Expr3",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=a9a18b9680a4cc18b339a22d4b12a8b5 (do not edit this line) */
