/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.4 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR0 = 1;
  public int JJTSYMBOL = 2;
  public int JJTEQUALS = 3;
  public int JJTVOID = 4;
  public int JJTADD = 5;
  public int JJTSUB = 6;
  public int JJTMUL = 7;
  public int JJTDIV = 8;
  public int JJTTERM = 9;


  public String[] jjtNodeName = {
    "Expression",
    "Expr0",
    "Symbol",
    "Equals",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=d52251cdbbcf4f1d6bfad379eaea6e58 (do not edit this line) */
